#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "functions.h"

//Steven Killoran

task main(){

	bool skippedStartLine = false; //this is just to skip the inital start box as it is also a black line.
	bool lineFollowerFlag = false;
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;

	while (SensorValue[sonarSensor] > 20 || SensorValue[sonarSensor] <= 0 ){ //47

		moveForwardWithEncoders();//moveForward();

		if(SensorValue[centerLineFollower]>1200){
			if(skippedStartLine == false){
				skippedStartLine = true;
				moveForwardWithEncodersWithWaitAndSpeed(20,100);//moveForward();
				continue;
			}

			if((SensorValue[centerLineFollower]>1300 && (SensorValue[sonarSensor] > 50 || SensorValue[sonarSensor] < 0)) ){ //leftTurnFlag == false &&
				moveForwardWithEncodersWithWaitAndSpeed(100,21); //passing in 21 due to the robot stopping motor function at anything less than 20, and if the encoders are not equal, it subtracts and goes less than 20
				leftTurnWithEncoders();
			}

			lineFollowerFlag = lineFollower(70, 30);
			waitUntil(lineFollowerFlag);
			wait10Msec(3);

			grabObject();
			reverse();

			leftTurnWithEncoders();//leftTurn();
			leftTurnWithEncoders();//leftTurn();

			lineFollower(50, 10);

			rightTurnWithEncoders();//rightTurn();

			dropObjectAtStart();

		}//top if


	}//while


}//main/task
